services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/imdb?useSSL=false
      SPRING_DATASOURCE_USERNAME: hoang
      SPRING_DATASOURCE_PASSWORD: aqws12345zx
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:12.1.2-ubi10
    environment:
      MARIADB_ROOT_PASSWORD: aqws12345zx
      MARIADB_DATABASE: imdb
      MARIADB_USER: hoang
      MARIADB_PASSWORD: aqws12345zx

  frontend:
    ports:
      - "80"